name: road
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.11.17
  - cairo=1.16.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - eigen=3.4.0
  - expat=2.5.0
  - ffmpeg=4.2.2
  - fontconfig=2.14.1
  - freetype=2.10.4
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.1.2
  - gnutls=3.6.15
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - icu=58.2
  - jpeg=9e
  - krb5=1.20.1
  - lame=3.100
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.2.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=11.2.0
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libopenblas=0.3.20
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - mysql=5.7.24
  - ncurses=6.4
  - nettle=3.7.3
  - opencv=4.6.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - pcre=8.45
  - pip=23.3.1
  - pixman=0.40.0
  - python=3.10.0
  - python_abi=3.10
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - x264=1!157.20191217
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - altair==5.1.2
      - annotated-types==0.6.0
      - anyio==3.7.1
      - attrs==23.1.0
      - blinker==1.7.0
      - cachetools==5.3.2
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.0
      - cycler==0.12.1
      - dill==0.3.7
      - exceptiongroup==1.2.0
      - fastapi==0.104.1
      - filelock==3.13.1
      - fonttools==4.45.1
      - fsspec==2023.10.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - h11==0.14.0
      - idna==3.6
      - importlib-metadata==6.8.0
      - jinja2==3.1.2
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.1
      - kiwisolver==1.4.5
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - packaging==23.2
      - pandas==2.1.3
      - pillow==10.1.0
      - protobuf==4.25.1
      - psutil==5.9.6
      - py-cpuinfo==9.0.0
      - pyarrow==14.0.1
      - pydantic==2.5.2
      - pydantic-core==2.14.5
      - pydeck==0.8.1b0
      - pygments==2.17.2
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - referencing==0.31.0
      - requests==2.31.0
      - rich==13.7.0
      - rpds-py==0.13.1
      - scipy==1.11.4
      - seaborn==0.13.0
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - starlette==0.27.0
      - streamlit==1.28.2
      - sympy==1.12
      - tenacity==8.2.3
      - thop==0.1.1-2209072238
      - toml==0.10.2
      - toolz==0.12.0
      - torch==2.1.1
      - torchvision==0.16.1
      - tornado==6.3.3
      - tqdm==4.66.1
      - triton==2.1.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - tzlocal==5.2
      - ultralytics==8.0.218
      - urllib3==2.1.0
      - uvicorn==0.24.0.post1
      - validators==0.22.0
      - watchdog==3.0.0
      - zipp==3.17.0
